# Generated by Django 5.1.1 on 2025-02-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_team_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
                ('placar_casa', models.IntegerField()),
                ('placar_fora', models.IntegerField()),
                ('tipo_competicao', models.CharField(max_length=200)),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_casa', to='teams.team')),
                ('time_fora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_fora', to='teams.team')),
            ],
        ),
    ]
