# Generated by Django 5.1.6 on 2025-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='data_partida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
