# Generated by Django 5.1.1 on 2025-02-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField(default=1900)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/')),
            ],
        ),
    ]
