# Generated by Django 5.1.1 on 2025-02-12 18:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
