# Generated by Django 4.2.7 on 2025-02-13 02:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_alter_player_nationality'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jogados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)])),
                ('gols', models.IntegerField(default=0)),
                ('assistencia', models.IntegerField(default=0)),
                ('passes_certos', models.IntegerField(default=0)),
                ('passes_errados', models.IntegerField(default=0)),
                ('desarmes', models.IntegerField(default=0)),
                ('cartao_vermelho', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('cartao_amarelo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('nota', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.matches')),
            ],
        ),
    ]
