# Generated by Django 5.1.1 on 2025-02-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0001_initial'),
        ('players', '0002_alter_player_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerDesempenhoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gols', models.IntegerField(default=0)),
                ('total_assistencias', models.IntegerField(default=0)),
                ('total_passes_certos', models.IntegerField(default=0)),
                ('total_passes_errados', models.IntegerField(default=0)),
                ('total_desarmes', models.IntegerField(default=0)),
                ('total_cartoes_vermelhos', models.IntegerField(default=0)),
                ('total_cartoes_amarelos', models.IntegerField(default=0)),
                ('media_nota', models.FloatField(default=0.0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
        ),
    ]
