# Generated by Django 5.1.6 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_stats', '0002_playerdesempenhogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdesempenhogeral',
            name='total_partidas',
            field=models.IntegerField(default=0),
        ),
    ]
