# Generated by Django 5.1.6 on 2025-05-09 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
        ('players', '0002_alter_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerencia.responsavel', verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('espera', 'Em espera'), ('desligado', 'Desligado')], default='ativo', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='player',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gerencia.turma', verbose_name='Turma (opcional)'),
        ),
    ]
