# Generated by Django 5.1.6 on 2025-05-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_remove_turma_faixa_etaria'),
        ('players', '0003_player_responsavel_player_status_player_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('falta', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='players.player')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faltas', to='gerencia.turma')),
            ],
        ),
    ]
