# Generated by Django 5.1.6 on 2025-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_faltas_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_faltas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
